---
spring:
  profiles: dev
  cloud:
    config:
      server:
        git:
          uri: https://github.com/x-cloud-school/xcs-environments
          default-label: master
security:
  basic:
    enabled: false
---
