spring:
  profiles:
    active: dev
---
spring:
  profiles: dev
  cloud:
    config:
      server:
        git:
          uri: https://github.com/x-cloud-school/xcs-environments
          default-label: master
server:
  port: 8888
---
